# Site Info
title:              "VOID001's WOWO"
description:        "Thinking, Coding, Improving"
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-73703130-1 # Put your Google Analytics code

# Author Info
author_name:        "VOID001"
author_email:       contact@void-shana.moe
author_gravatar:    2c230611acf61701a6666dd919b12073 # Gravatar md5 hash

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /posts/:title # Post permalink
timezone:           Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

future:             TRUE

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "recover"]
gems:
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-feed

liquid:
    error_mode: warn

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
